name: Use upload artifact
on:
  push:
  workflow_dispatch:

jobs:
  publisher:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest,macos-latest]
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      git_user: mnnna
      git_email: 850400628@qq.com
      ___X_CMD_CODESORUCE_REPO: dev
      CONCURRENCY: 10
    steps:
    - uses: actions/checkout@v3

    - run: mkdir -p path/to/artifact

    - run: echo hellornkgjn > path/to/artifact/wofffrld.txt

    - uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: path/to/artifact/world.txt