name: Use upload artifact
on:
  push:
  workflow_dispatch:

jobs:
  publisher:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      git_user: mnnna
      git_email: 850400628@qq.com
      ___X_CMD_CODESORUCE_REPO: dev
      CONCURRENCY: 10
    test-diff-os:
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
  
  test-diff-image:
    strategy:
      matrix:
        image:
          - xcmd/base-ubuntu-2-dev
          - xcmd/base-debian-2-dev
          - xcmd/base-alpine-2-dev
          - xcmd/base-bash3-2-dev
          - xcmd/base-bash4-2-dev
          - xcmd/base-bash5-2-dev
          - xcmd/base-centos-2-dev
          - xcmd/base-archlinux-2-dev
          - xcmd/base-fedora-2-dev
    container:
      image: ${{ matrix.image }}
    runs-on: ubuntu-latest
    steps:
      - name: main
        run: tpye x
