name: Use upload artifact
on:
  push:
  workflow_dispatch:

jobs:
  publisher:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest,macos-latest]
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      git_user: mnnna
      git_email: 850400628@qq.com
      ___X_CMD_CODESORUCE_REPO: dev
      CONCURRENCY: 10
    steps:
      - name: main
        uses: x-cmd/action@main
        with:
          code: |
            x env use deno;\
            x env use go;\
            x env use julia;\
            x env use java=open-18;\
            x env use kotlin;\
            x env use lua;\
            x env use node;\
            x env use perl;\
            x env use python;\
            x env use rust;\
            x env use scala;\
            
